import java.sql.*;
import java.time.LocalDate;

public class EmployeePayroll {

    public EmployeePayrollData addEmployeeToEmployeePayroll(String name, String gender, double salary, LocalDate startDate) {
        String jdbcUrl = "jdbc:mysql://localhost:3306/employee_payroll_service";
        String username = "root";
        String password = "superstars";

        String sql = String.format("insert into employee_payroll(name,gender,salary,startDate)" +
                "values('%s','%s','%s','%s')", name, gender, salary, Date.valueOf(startDate));
        /*
        Intialising employeePayrollData to null
         */
        EmployeePayrollData employeePayrollData = null;
        try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password);) {

            int employeeId = -1;
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            /*
            If there is update in the database it will return generated keys and rowsAffected has value 1

             */
            int rowAffected = preparedStatement.executeUpdate(sql, preparedStatement.RETURN_GENERATED_KEYS);
/*
if row is affected then it will generate the key which Retrieves any auto-generated keys created as a result
 of executing this Statement object
 */
            if (rowAffected == 1) {
                ResultSet resultSet = preparedStatement.getGeneratedKeys();
         /*
         Saving the autogenerated key in the employeeId
          */

                if (resultSet.next()) {
                    employeeId = resultSet.getInt(1);
                }
            /*
            adding the data to the employeePayrollData object for comparing  and return it to use in testCase
            */

                employeePayrollData = new EmployeePayrollData(employeeId, name, salary, startDate);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return employeePayrollData;
    }


    public boolean checkEmployeePayrollInSyncWithDb(String name) {
        String jdbcUrl = "jdbc:mysql://localhost:3306/employee_payroll_service";
        String username = "root";
        String password = "superstars";
        boolean result = false;

        try {
            Connection connection = DriverManager.getConnection(jdbcUrl, username, password);

            PreparedStatement preparedStatement = connection.prepareStatement("select * from employee_payroll");
        /*
        A ResultSet object is a table of data representing a database result set, which is usually generated by executing
        a statement that queries the database.The object of ResultSet maintains a cursor pointing to a row of a table
        */
            ResultSet resultSet = preparedStatement.executeQuery();
        /*
        We are traversing in the database using resultSet.next if there is name in the database is equal to
        the name given in the method name checkEmployeePayrollInSyncWithDb then return true else return false
         */
            while (resultSet.next()) {

                if (resultSet.getString("name").equalsIgnoreCase(name)) {
                    result = true;
                } else {
                    result = false;
                }
            }
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return result;
    }
}


